### ISSUE TITLE
How to notify reader after writer update?

### ISSUE THREAD

**Issue by rain2307** [cloudflare/mmap-sync#10]
`Condvar` use mutex I think it's a bad idea?
What's the right way? Thanks.

**Comment by kurkpitaine** [comment]
I think it would be useful to enumerate the available solutions:
- Use inotify/kqueue to watch for file changes.
- Use signalling via syscalls, eg: SIGUSR1/2. Requires the readers to register their pid into the state file.
- A pipe or unix socket.

Or maybe something else I missed?
