### ISSUE TITLE
Configurable SLEEP_DURATION

### ISSUE THREAD

**Issue by lso400** [cloudflare/mmap-sync#13]
The `SLEEP_DURATION` is hardcoded to one second, can we make that configurable?

**Comment by bocharov** [comment]
We could consider making `SLEEP_DURATION` configurable, but first I'd like to understand your use case a bit better.
Is current default of 1 second too much or too little? There is also `grace_duration` parameter of `Synchronizer::write` method, which is configurable and related to the same logic of preventing "dead readers" problem.

**Comment by lso400** [comment]
> We could consider making `SLEEP_DURATION` configurable, but first I'd like to understand your use case a bit better. Is current default of 1 second too much or too little? There is also `grace_duration` parameter of `Synchronizer::write` method, which is configurable and related to the same logic of preventing "dead readers" problem.

Hey thanks for looking into this. One second is too long for us. I think `grace_duration` does not solve the issue we're seeing
E.g. We set `grace_duration` to 100ms. When `num_readers`>0 but `Instant::now() < grace_expiring_at`, the thread will be blocked for 1 second. We want to block for say 10ms and check `num_readers` again.

**Comment by bocharov** [comment]
Thanks for explaining your use case in more detail. I think we can definitely make this configurable - would you prefer it as template parameter on `Synchronizer` struct, which we can configure to default 1s (still configurable) and not break existing methods signature or perhaps new parameter to existing method or completely new method with new parameter?

**Comment by lso400** [comment]
> template parameter on Synchronizer struct, which we can configure to default 1s (still configurable)

This sounds good to me!

**Comment by bocharov** [comment]
Perhaps, other alternative is to add `tokio` optional feature, which will use `tokio::time::sleep` instead of `std::thread::sleep`, which doesn't block the thread during the sleep and allows other workload to progress.

**Comment by lso400** [comment]
> Perhaps, other alternative is to add `tokio` optional feature, which will use `tokio::time::sleep` instead of `std::thread::sleep`, which doesn't block the thread during the sleep and allows other workload to progress.

I'm afraid that this will not be helpful to applications running in sync runtime. IMO making it a template parameter on `Synchronizer` struct makes most sense

**Comment by bocharov** [comment]
Sure, I'll make template parameter change and release new package version tomorrow.

**Comment by bocharov** [comment]
@lso400 change now has been implemented and released as package version `1.0.4` via https://github.com/cloudflare/mmap-sync/pull/14

**Comment by lso400** [comment]
Thanks for the prompt action, much appreciated!
