### ISSUE TITLE
unsafe read & grace duration

### ISSUE THREAD

**Issue by nbittich** [cloudflare/mmap-sync#2]
First of thanks for open-sourcing this crate, it seems to fit my need perfectly.
It would be nice to provide a little bit more documentation regarding read being unsafe .
It returns a Result of ```mmap_sync::guard::ReadResult```, and the documentation seems to say it's safe  at this point (```The guard module provides a safe interface for accessing shared memory.```). I'm a bit confused here.

Regarding the grace_duration, is it some sort of timeout? 

Thanks a lot.

**Comment by bocharov** [comment]
Sure, here's a more concise version:

Thank you for your valuable feedback. We've addressed your concerns in the documentation:

- Explanation of `grace_duration` in the `write` method is enhanced for clarity.
- Safety considerations regarding the `read` method have been further detailed.
- `ReadGuard` module description is revised to accurately describe its purpose and role.

You can see these changes in this commit: [e41fefa](https://github.com/cloudflare/mmap-sync/commit/e41fefa1b26a600ef23d8f9f43cf66b91686f8bf).

Please let us know if there are any other areas of confusion. Your feedback greatly helps us improve `mmap-sync`.
